speakeasy-api/gram

client/dashboard/src/components/ui/tooltip.tsx
The esteemed @chase-crumbaugh points out that our tooltips have some strange text layout behavior. Line wraps seem to produce excessive whitespace on the right margin. For example,
This is somewhat not obvious how to fix uniformly because I think text layout is calculated after width is, so it's difficult to convince CSS to go back and adjust to working layouts. One remediation is to switch from `text-wrap: balance` to `text-wrap: pretty`. Balance is intended to work with extremely short text (like titles) rather than prose where pretty is more suitable.
We can also reduce the width of these containers in general from 600px to tailwind's small container size (384px). We should probably keep an eye out for larger content, but Chase and I did a spot check and things are seemingly pretty …
=> feat: change text wrap for more pleasing layout

server/cmd/gram/deps.go, server/cmd/gram/start.go, server/cmd/gram/worker.go, server/internal/assets/setup_test.go, server/internal/auth/setup_test.go, server/internal/billing/stub.go, server/internal/deployments/setup_test.go, server/internal/environments/setup_test.go, server/internal/instances/impl.go, server/internal/keys/setup_test.go, server/internal/mcp/rpc_tools_call.go, server/internal/templates/setup_test.go, server/internal/thirdparty/polar/client.go, server/internal/tools/setup_test.go, server/internal/toolsets/setup_test.go, server/internal/variations/setup_test.go
This change updates tracking and repository calls to emit tracing spans that we can observe in o11y dashboards. The key change for tracking:
```diff
- go s.billing.TrackToolCallUsage(context.Background(), billing.ToolCallUsageEvent{
+ go s.billing.TrackToolCallUsage(context.WithoutCancel(ctx), billing.ToolCallUsageEvent{
```
This retains the trace and parent span across tracking calls.
=> chore: enable tracing of billing operations

client/dashboard/src/components/app-sidebar.tsx, client/dashboard/src/components/content-error-boundary.tsx, client/dashboard/src/components/page-layout.tsx, client/dashboard/src/pages/toolsets/Toolset.tsx, server/internal/usage/impl.go
Improves the content error boundary to capture more cases
Also, prevents a billing endpoint failure from crashing the page due to the sidebar notification being out of the error boundary
=> fix: Improve error boundary

.mise-tasks/zero/tls.sh
Allow turning off TLS by changing the scheme of all endpoints to `http`.
_The supported flow for all browsers is to keep TLS enabled. But, this change is an escape hatch for local devs who don’t want to trust a new root CA, or if their local development environment makes it unwieldy (e.g. certain local VM development)._
1. `mkcert -uninstall` (this also requires system password)
2. Run `./zero`
3. Script prompts for sudo password at the `mkcert -install` step with a log for how to turn it off.
4. Open :5173 in any browser, and it works.
1. Update both `GRAM_SERVER_URL` and `GRAM_SITE_URL` to use `http://` instead of `https://`
2. Run `./zero`
3. Script warns that TLS is off, and updates `mise.local.toml` with empty values for `GRAM_SSL_CERT_FILE` and `GRAM_SSL_KEY_FILE`
5. Open :5173 in …
=> feat: Allow plain HTTP for local development

server/internal/billing/repository.go, server/internal/billing/stub.go, server/internal/thirdparty/polar/client.go, server/internal/usage/impl.go
Adds a fallback successURL to the polar checkout link in the event that the embedded checkout doesnt work
=> fix: Add success url to polar checkout link

server/internal/o11y/setup.go, server/internal/o11y/setup_test.go
Fixes AGE-503
This change adds a basic smoke test to ensure OpenTelemetry can be set up with out an error. Previously, updates to the semconv package via dependabot PRs could cause runtime errors like this:
```
create resource: conflicting Schema URL: https://opentelemetry.io/schemas/1.37.0 and https://opentelemetry.io/schemas/1.34.0
```
This is caught by the smoke test now and updates to semconv will cause build failure if the codebase is not updated accordingly to use the new semconv version everywhere.
=> chore: add smoke test for OTel setup code

.changeset/config.json
The automated version PR that the changesets action creates contains a `s-kip ci` directive (dash inserted deliberately) which prevents the CI jobs from running. This in turn means that branch protection rules that require certain jobs to pass will never be satisfied and the versioning PR cannot be merged.
This change disables the directive in changesets so that the CI jobs run.
=> fix: disable skip ci directive in changesets

.changeset/tame-humans-spend.md, client/dashboard/src/pages/playground/ChatWindow.tsx
This change solves a nil deference issue in the tool name callbacks of the `ChatWindow` component. The `args` argument passed to `JSON.stringify` was sometimes `undefined` and `JSON.stringify(undefined) ===  undefined` so `JSON.stringify(undefined).includes(...)` would throw a runtime error that was seen in logs.
=> fix: avoid nil reference for toolName in ChatWindow

server/cmd/gram/deps.go, server/cmd/gram/start.go, server/cmd/gram/worker.go, server/internal/assets/assetstest/store.go, server/internal/assets/store.go
This change implements the io.ReaderAt interface for the assets backends, this interface is essential for Gram Functions and efficient random access of zip archives and to open these with `zip.NewReader`.
The Google Cloud Storage backend implementation uses HTTP range requests to implement this interface.
=> chore: implement io.ReaderAt for assets backends

server/.golangci.yaml
This change updates golangci-lint configuration to ensure that all issues found during linting are printed, without any limits.
=> chore: print all issues found during go linting

.changeset/twelve-bats-throw.md, server/internal/thirdparty/polar/client.go
This change updates the polar client to add the organization ID as an attribute to various tracing spans. This will help us better track down affected organizations when investigating issues related to billing.
=> fix: include org id in tracing spans for polar

.changeset/four-apes-sneeze.md, server/internal/variations/listglobal_test.go
Example of a flaking test: https://github.com/speakeasy-api/gram/actions/runs/17747820124/job/50436818163?pr=260
=> fix: add sleep to testvariationsservice listglobal orderedbyid

client/dashboard/src/pages/deployments/ToolsList.tsx, client/dashboard/src/pages/toolsets/ToolSelect.tsx
We currently show summary and description for tools in the UI. However, this is confusing because we don't actually use the summary for anything. For example, it looks like it should be editable when you go to edit a tool description, but what actually pops up is _just_ the description. The summary is entirely uneditable. This PR clarifies things by simply not showing the summary, which also opens the door to no longer populating this field
=> chore: stop showing summary in UI

server/internal/deployments/events/log.go, server/internal/openapi/process.go
This change moves the deployment events logger to an events package under the deployments package. It used to be in the openapi package but the exact functionality is needed to log events when processing Gram functions so it was lifted out to a more appropriate package.
=> chore: move events logger to deployments subpackage

server/internal/attr/conventions.go, server/internal/background/activities/metrics.go
This change introduces o11y attributes and metrics used to monitor processing of Gram Functions as part of deployments.
=> chore: define o11y attributes and metrics for Gram Functions

.changeset/twenty-tires-enjoy.md, server/cmd/gram/start.go, server/cmd/gram/worker.go, server/internal/attr/conventions.go, server/internal/background/activities.go, server/internal/background/activities/metrics.go, server/internal/background/activities/process_deployment.go, server/internal/background/worker.go, server/internal/deployments/setup_test.go, server/internal/openapi/extract_test.go, server/internal/openapi/process.go, server/internal/tools/setup_test.go, server/internal/toolsets/setup_test.go
This change adds an explicit tracing span around the openapi tool extractor so we can observe processing times and chosen parsers in traces. Additionally, related metrics have also been updated to include the chosen parser as an attribute.
=> chore: add OTel tracing around OpenAPI processing

server/internal/urn/errors.go, server/internal/urn/format.go, server/internal/urn/tools.go, server/internal/urn/tools_test.go
Package `urn` introduces a naming convention for uniquely identifying tools across Gram clients and servers that also works well for URL embedding and database lookups.
The format is `<kind>:<source>:<name>`, where:
- **kind** the type of the tool such as `http` and `function`
- **source**: the deployment artifact from which the tool was generated.
- **name**: the name of the tool.
The new type `urn.Tool` will also be a column type used in both Goa and SQLc as it implements (un)marshallers for json and sql.
=> chore: add package `urn` for addressing tools

client/dashboard/package.json, client/dashboard/src/pages/deployments/Deployments.tsx, pnpm-lock.yaml
Adds a badge to the table row that is the active deployment (the latest deployment with a status of "completed").
=> fix: denote active deployment in deployments page

server/database/schema.sql, server/internal/database/models.go, server/internal/deployments/queries.sql, server/internal/deployments/repo/models.go, server/internal/deployments/repo/queries.sql.go, server/internal/openapi/extract_libopenapi.go, server/internal/openapi/extract_speakeasy.go, server/internal/templates/impl.go, server/internal/templates/queries.sql, server/internal/templates/repo/models.go, server/internal/templates/repo/queries.sql.go, server/internal/testenv/testrepo/models.go, server/internal/testenv/testrepo/queries.sql.go, server/internal/tools/repo/models.go, server/internal/tools/repo/queries.sql.go, server/internal/toolsets/repo/queries.sql.go, server/internal/urn/format.go, server/migrations/20250918183732_add-tool-urn-to-tables.sql, server/migrations/atlas.sum
This PR:
- Adds `tool_urn` (nullable) columns to `http_tool_definitions` and `prompt_templates`
- Begins writing to these columns. The URN structure for `prompt_templates` is `tools:prompt:<kind>:<name>`
This change is virtually riskless as it is write-only and the columns are nullable
Next steps:
- Write + run backfill script to fill these columns
- Make the columns non-nullable
=> chore: start writing tool_urns to existing tool types

server/internal/background/activities/process_deployment.go, server/internal/openapi/extract_libopenapi.go, server/internal/openapi/extract_speakeasy.go, server/internal/openapi/extract_test.go, server/internal/openapi/process.go
This change wraps the libopenapi and speakeasy openapi parsing logic with a tracing span, allowing us to analyze the performance of each as part of deployment processing.
=> chore: add tracing span around openapi parsing

server/internal/keys/createkey_test.go, server/internal/keys/revokekey_test.go
Running multiple tests against the shared test context causes race conditions.
<details>
<summary>Proved with a simple test 👇</summary>
```go
package keys_test
import (
"testing"
"time"
"github.com/stretchr/testify/require"
gen "github.com/speakeasy-api/gram/server/gen/keys"
)
func TestDatabaseIsolation(t *testing.T) {
t.Parallel()
// Shared context and service (same pattern as revokekey_test.go)
ctx, ti := newTestKeysService(t)
t.Run("test1 creates key", func(t *testing.T) {
t.Parallel()
// Create a key
_, err := ti.service.CreateKey(ctx, &gen.CreateKeyPayload{
SessionToken: nil,
Name:         "isolation-test-key-1",
Scopes:       []string{"consumer"},
})
require.NoError(t, err)
// Small delay to let other tests see this key
time.Sleep(50 * time.Millisecond)
})
t.Run("test2 counts keys", …
```
=> chore: fix race condition in key revocation unit tests

.changeset/four-seals-count.md, server/internal/thirdparty/openrouter/openrouter.go, server/internal/thirdparty/openrouter/queries.sql, server/internal/thirdparty/openrouter/repo/queries.sql.go
The current openrouter key refresh logic was flawed. Although we set the credit limit of the key correctly, with the way openrouter works the usage that is applied to that key never resets.
The best option right now is to create a new fresh key on the monthly refresh and clean up the old one.
Eventually we've talked about moving this to be centrally metered and not creating keys per org. We should still eventually move in that direction, but this is a change that will make our current system behave correctly.
=> fix: openrouter key refresh

.changeset/ready-aliens-end.md, cli/internal/api/deployments.go, cli/internal/app/app.go, cli/internal/app/push.go, cli/internal/app/status.go, cli/package.json
Add `gram status` command to display deployment information.
Use the implementation for polling a new deployment after `gram push`.
Optionally skip polling with `—skip-poll`.
<details>
<summary>Polling after push</summary>
```bash
$ go run . push --config config-22.json --idempotency-key $(uuidgen) \
--api-url https://dev.getgram.ai \
--api-key “$(dev-api-key)" \
--project test-4
{"time":"2025-09-24T16:58:14.716232-07:00","level":"INFO","source":{"function":"github.com/speakeasy-api/gram/cli/internal/app.newPushCommand.func1","file":"/Users/babe/code/speakeasy/gram/cli/internal/app/push.go","line":118},"msg":"Deploying to project","project":"test-4","config":"/Users/babe/code/speakeasy/gram/cj_stuff/bulk-insert-regression-test/configs/config-22.json"} …
```
=> feat: gram status

.changeset/pink-singers-speak.md, server/internal/gateway/proxy.go, server/internal/gateway/security.go
- Adds consistent trace id to tool call requests that the customer can use to search their entire logs from gram logs
- Can discuss if we actually want to use the `otelhttp` transport. This is possible with out it.
=> feat: add consistent trace id to tool requests

.changeset/tender-views-cry.md, server/cmd/gram/start.go, server/internal/mcp/impl.go
Broke this while moving handlers around per: https://speakeasy-dev.slack.com/archives/C07ME0HG1V5/p1759506656578509?thread_ts=1758576660.197199&cid=C07ME0HG1V5
=> fix: restore install page location

.mise-tasks/build/functions-bin.sh, .mise-tasks/build/functions-local.sh, functions/cmd/runner/main.go, functions/internal/attr/conventions.go
This change adds a mise task to build the gram runner nodejs22 image for use during local development. As part of this task, it is loaded into the local docker daemon so that it can be used by the server to provision function runner containers.
=> chore: add `mise run build:functions-local`

.mise-tasks/db/rewind.mts
This change adds a new mise task to undo a series of database migrations during local development. This is useful because we can edit the db schema repeatedly during development and making it easy to rewind -> re-diff -> reapply migrations speeds the iteration loop considerably.
https://github.com/user-attachments/assets/9121fb83-4d79-4efa-a3f7-0db35809bb1d
=> chore: add mise db:rewind to undo migrations

.goreleaser.yaml
Only make changelogs using `changsets`.
Only GitHub release changelogs are affected by this change.
Multiple versioning tags/releases are causing some confusing output. Our environment includes:
1. `pnpm changeset`
2. `TriPSs/conventional-commits`
3. `GoReleaser`
It leads to CLI releases on Github with non-related changelog (example: [0.6.0](https://github.com/speakeasy-api/gram/releases/tag/0.6.0)).
Going forward, we will leave the changelog generation `changeset`, like we do for `@gram/server`.
=> chore: disable changelog from goreleaser

.changeset/fluffy-planets-enjoy.md, client/dashboard/src/components/ui/slider.tsx, client/dashboard/src/pages/playground/ChatWindow.tsx
- Added temperature slider control in playground chat interface
- Added new Slider UI component
- Enhanced ChatWindow with temperature control
=> feat: temperature slider in the playground
