speakeasy-api/gram

server/internal/thirdparty/polar/client.go
=> fix: Account for no customer state

client/dashboard/src/pages/home/Home.tsx, client/dashboard/src/pages/playground/ChatWindow.tsx, client/dashboard/src/pages/playground/Playground.tsx, client/dashboard/src/pages/playground/PlaygroundRHS.tsx, client/dashboard/src/pages/toolBuilder/ToolBuilder.tsx, client/dashboard/src/pages/toolsets/ToolSelect.tsx, client/dashboard/src/pages/toolsets/ToolsetEnvironmentBadge.tsx
https://github.com/user-attachments/assets/02463c64-50c6-4bea-aad6-9f3f63f9bc53
* Adds PlaygroundPrompt as the 1st section
* Moves actions up the page
* Improves card hierarchy
* Introduces inline card actions
=> feat: Update home page design

client/dashboard/src/contexts/Auth.tsx, client/dashboard/src/pages/mcp/MCPDetails.tsx
Bug found, differnece between local and live behavior
=> fix: Dashboard not loading

client/dashboard/src/App.tsx, client/dashboard/src/pages/toolsets/openapi/OpenAPI.tsx
https://github.com/user-attachments/assets/0244efc4-af2d-4c61-ae9d-70c920a25521
=> feat: add sonner toasts and feedback to api deletion

docs/runbooks/adding-and-modifying-endpoints.md, docs/runbooks/writing-queries-with-sqlc.md
This change improves documentation accuracy and clarity by providing a more precise description of how we use Goa in our API development process.
Documentation only - no functional changes. Helps new developers better understand our API development approach.
=> feat: Add a runbook for adding and modifying endpoints

client/dashboard/src/pages/environments/Environment.tsx
https://github.com/user-attachments/assets/1df814db-7e69-4530-863f-313d3f473774
=> feat: update environment page form to page toolset auth tab experience

client/dashboard/src/pages/billing/Billing.tsx, server/internal/thirdparty/polar/client.go
* fix: add includedBullets check in billing page
=> chore: update pricing bullets

server/internal/toolsets/impl.go
We want to enable the first available server in an org not in a project
=> feat: enable first server in an org

client/dashboard/src/pages/billing/Billing.tsx
Mistakenly committed testing setup
=> fix: Remove extra upgrade cta

server/cmd/gram/start.go, server/internal/usage/impl.go
Forward subscription changes to posthog for tracking purposes
=> chore: capture subscription changes in posthog

.changeset/kind-dots-lick.md, client/dashboard/public/external/fflate.js, client/dashboard/public/external/hosted-install-page.js, server/internal/mcp/hosted_page.html.tmpl
Missed a couple important details on my way out the door.
@chase-crumbaugh
=> fix: add actual install page assets and use env var

client/dashboard/src/pages/deployments/Deployments.tsx
=> feat: report redeploy status via toast

client/dashboard/src/pages/toolsets/openapi/OpenAPI.tsx
=> feat: add deletion warning for api sources

client/dashboard/src/pages/deployments/Deployment.tsx, client/dashboard/src/pages/deployments/DeploymentTabs.tsx
=> feat: deployment overview page layout improvements

client/dashboard/src/pages/toolsets/ToolSelect.tsx, server/database/sqlc.yaml, server/internal/database/models.go, server/internal/deployments/repo/models.go, server/internal/deployments/repo/queries.sql.go, server/internal/openapi/extract_libopenapi.go, server/internal/openapi/extract_speakeasy.go, server/internal/templates/impl.go, server/internal/templates/repo/models.go, server/internal/templates/repo/queries.sql.go, server/internal/testenv/testrepo/models.go, server/internal/tools/repo/models.go, server/internal/toolsets/impl.go, server/internal/toolsets/queries.sql, server/internal/toolsets/repo/models.go, server/internal/toolsets/repo/queries.sql.go
This will be merged when the backfill script is ready to go to minimize the time these additional queries are in place
=> chore: start creating toolset_versions

.changeset/hungry-dingos-think.md
=> fix: fix changeset that was breaking the changeset lint

.mise-tasks/zero/tls.sh
fixes: #282
- when setting up a project locally in a wsl env, cert is getting installed successfully but in linux env, but its not propogating properly to windows store 
- I've added a check to detect if the setup env in wsl and added suggestive instructions to switch to `http` as suggessted by @simplesagar in #282
Unsecure Warnings Before (Using HTTPS):
After (Using HTTP: Running 
```mise set --file mise.local.toml GRAM_SERVER_URL=http://localhost:8080" ``` &
```mise set --file mise.local.toml GRAM_SITE_URL=http://localhost:5173")``` :
=> chore: local WSL setup suggest http methods

client/dashboard/src/pages/onboarding/UploadOpenAPI.tsx
=> fix: remove brand variant from upload button

.changeset/yummy-trees-report.md, server/cmd/gram/deps.go, server/cmd/gram/start.go, server/cmd/gram/worker.go, server/internal/billing/tracking.go, server/internal/instances/impl.go, server/internal/mcp/rpc_tools_call.go, server/internal/thirdparty/tracking/impl.go
- Creates a composite client for us track usage data we send to polar in posthog as well.
- Removes the direct dependency on posthog from the instances service.
=> feat: billing usage tracking federation

client/dashboard/src/pages/billing/Billing.tsx, server/internal/thirdparty/polar/client.go
=> chore: update billing tier bullets

client/dashboard/src/pages/home/Home.tsx, client/dashboard/src/pages/toolsets/Toolsets.tsx, client/dashboard/src/pages/toolsets/openapi/OpenAPI.tsx
=> feat: use ServerCard component on Toolset page
